# Generated by Django 2.0.13 on 2019-04-07 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proiect',
            options={'verbose_name': 'Proiect', 'verbose_name_plural': 'Proiecte'},
        ),
    ]
