# Generated by Django 2.2 on 2019-11-21 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0002_auto_20190407_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='proiect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='images', to='hub.Proiect'),
        ),
    ]
