# Generated by Django 2.2 on 2019-11-23 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0003_auto_20191121_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='proiect',
            name='publish',
            field=models.BooleanField(default=True),
        ),
    ]
