# Generated by Django 2.2 on 2019-11-23 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0003_auto_20191121_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='proiect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='hub.Proiect'),
        ),
    ]
