# Generated by Django 2.2 on 2019-11-23 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0004_proiect_publish'),
        ('hub', '0004_auto_20191123_1154'),
    ]

    operations = [
    ]
