# Generated by Django 2.2.4 on 2019-12-02 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0005_merge_20191123_1157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proiect',
            options={'ordering': ['id'], 'verbose_name': 'Proiect', 'verbose_name_plural': 'Proiecte'},
        ),
    ]
